alter table _countries
  change country_id id bigint primary key auto_increment,
  change title_ru title varchar(150) not null,
  add index `country_title_index` (title),
  drop title_ua,
  drop title_be,
  drop title_en,
  drop title_es,
  drop title_pt,
  drop title_de,
  drop title_fr,
  drop title_it,
  drop title_pl,
  drop title_ja,
  drop title_lt,
  drop title_lv,
  drop title_cz;

alter table _regions
  change region_id id bigint primary key auto_increment,
  change title_ru title varchar(200) not null,
  modify country_id bigint not null,
  add index `region_title_index` (title),
  add foreign key (country_id) references _countries (id),
  drop title_ua,
  drop title_be,
  drop title_en,
  drop title_es,
  drop title_pt,
  drop title_de,
  drop title_fr,
  drop title_it,
  drop title_pl,
  drop title_ja,
  drop title_lt,
  drop title_lv,
  drop title_cz;

delete from _cities where region_id is null;
alter table _cities
  change city_id id bigint auto_increment,
  change title_ru title varchar(200) not null,
  modify country_id bigint not null,
  modify region_id bigint not null,
  add foreign key (country_id) references _countries (id),
  add foreign key (region_id) references _regions (id),
  add index `cities_title_index` (title),
  drop area_ru,
  drop region_ru,
  drop title_ua,
  drop area_ua,
  drop region_ua,
  drop title_be,
  drop area_be,
  drop region_be,
  drop title_en,
  drop area_en,
  drop region_en,
  drop title_es,
  drop area_es,
  drop region_es,
  drop title_pt,
  drop area_pt,
  drop region_pt,
  drop title_de,
  drop area_de,
  drop region_de,
  drop title_fr,
  drop area_fr,
  drop region_fr,
  drop title_it,
  drop area_it,
  drop region_it,
  drop title_pl,
  drop area_pl,
  drop region_pl,
  drop title_ja,
  drop area_ja,
  drop region_ja,
  drop title_lt,
  drop area_lt,
  drop region_lt,
  drop title_lv,
  drop area_lv,
  drop region_lv,
  drop title_cz,
  drop area_cz,
  drop region_cz;

